### ISSUE TITLE
Fail when issuing VC contains fields not defined in the context(s)

### ISSUE THREAD

**Issue by stevenvegt** [nuts-foundation/nuts-node#1132] opened 2022-05-19 16:02 UTC
It is possible to issue a new credential which contains fields that are not defined by the context(s). This results is a apparently valid and correct credential, however, the undefined fields are not used to calculate the signature hash and therefor, these fields are not protected by the signature. A user should be warned about this.

**Comment by woutslakhorst** [comment] 2022-05-20 05:57
duplicate of #1032

**Closed** 2022-06-10 04:40 UTC
Labels: vcr
