### ISSUE TITLE
Network: Failed to persist backoff error during shutdown/startup

### ISSUE THREAD

**Issue by stevenvegt** [nuts-foundation/nuts-node#1864] opened 2023-01-31 14:02 UTC
During a shutdown, the network is closed first, the storage later, but still a backoff occurs and tries to write to the already closed storage.

```
^CINFO[0411] Shutting down...                             
INFO[0411] Stopping HTTP...                              module=core
INFO[0411] Stopped HTTP                                  module=core
INFO[0411] Stopping Auth...                              module=core
INFO[0411] Stopped Auth                                  module=core
INFO[0411] Stopping Network...                           module=core
INFO[0411] Stopped Network                               module=core
INFO[0411] Stopping VDR...                               module=core
INFO[0411] Stopped VDR                                   module=core
INFO[0411] Stopping VCR...                               module=core
INFO[0411] Peer closed connection                        module=Network peerAddr="nuts-development.woutslakhorst.nl:5555" peerAuthenticated=true peerDID="did:nuts:HSr29Y6qFFSHGPzn9VK7dhpbT14U9epwPhMECRHBwdaQ" peerID=b82b1f07-2e4e-45aa-8691-6802a0a15be3 protocolVersion=2
INFO[0411] Stopped VCR                                   module=core
INFO[0411] Stopping Metrics...                           module=core
INFO[0411] Peer closed connection                        module=Network peerAddr="vps-knorretje.nl:5555" peerAuthenticated=true peerDID="did:nuts:CDVrL1vpaww14uf3ctF5aMeKnhDt4PqTdis3GPoVpcms" peerID=82784ed8-0e23-465e-beac-d316952a6a99 protocolVersion=2
INFO[0411] Stopped Metrics                               module=core
INFO[0411] Stopping Storage...                           module=core
INFO[0411] Stopped Storage                               module=core
INFO[0411] Stopping Events...                            module=core
ERRO[0411] Failed to persist backoff                     error="database error: database not open" module=Network
INFO[0411] Stopped Events                                module=core
INFO[0411] Shutdown complete. Goodbye!                  

Process finished with the exit code 0
```

**Comment by reinkrul** [comment] 2023-02-13 09:20
Not a very big problem i.m.o., do we actually want to solve this?

**Comment by woutslakhorst** [comment] 2023-02-13 12:11
Also at startup

**Comment by reinkrul** [comment] 2023-02-17 12:43
High-level issue https://github.com/nuts-foundation/nuts-node/issues/1900

**Comment by woutslakhorst** [comment] 2023-02-20 09:00
Another error is a write timeout.

**Comment by reinkrul** [comment] 2023-02-23 07:54
Should be fixed in https://github.com/nuts-foundation/nuts-node/pull/1874

**Comment by reinkrul** [comment] 2023-02-27 16:04
Shutdown race condition seems to be fixed, can't reproduce it any more.

Haven't witnessed the issue at start-up, closing issue for now. Can be reopened when new evidece is available.

**Closed by reinkrul** 2023-02-27 16:04 UTC
Labels: bug
