### ISSUE TITLE
Auth: RFC021 additional credentials + multiple DID methods enabled = failure

### ISSUE THREAD

**Issue by reinkrul** [nuts-foundation/nuts-node#3423] opened 2024-09-30 07:41 UTC
When a service access token is requested (RFC021) when multiple DID methods are enabled, and additional credential(s) (NutsEmployeeCredential) are provided, an error occurs;

```
multiple sign instructions not supported
```

This is probably due to the submission builder matching on VCs from multiple DIDs/wallets. It should probably try to fulfil the input descriptors using the same DID? Or at least sort them to make it generally succeed. Now it seems to always fail.

**Comment by woutslakhorst** [comment] 2024-09-30 08:28
duplicate of #3424

**Closed by woutslakhorst** 2024-09-30 08:28 UTC
Labels: bug, rc
